export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'



export const LOAD_LOGIN_REQUEST = 'LOAD_LOGIN_REQUEST'
export const LOAD_LOGIN_SUCCESS = 'LOAD_LOGIN_SUCCESS'
export const LOAD_LOGIN_FAIL = 'LOAD_LOGIN_FAIL'
 